name: backend-app workflow

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - develop
      - main

env: 
  DEBUG: 1
  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
  DOMAIN_NAME: 'www.domain.ru'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
        pip install -r bass/requirements.txt 
    - name: Test with flake8 and django tests
      run: |
        python -m flake8
        cd bass && python manage.py test

  send_message:
    runs-on: ubuntu-latest
    needs: tests
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    steps:
    - name: send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: TELEGRAM_TOKEN
        message: ${{ github.workflow }} успешно выполнен в ветку ${{ github.base_ref }} из ветки ${{ github.head_ref }}!
